server:
    port: 8080

spring:
    application:
        name: kafka-producer-app
    kafka:
        bootstrap-servers: 192.168.1.5:9092
        producer:
            bootstrap-servers: "192.168.1.5:9092"
            retries: 1
            #默认16k
            batch-size: 16384
            #默认30M
            buffer-memory: 33554432
            #推荐使用StringSerializer, 不同端处理时比较灵活
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            #0不需要确认, 1leader确认, -1(或all)全部确认
            acks: 1
