server:
    port: 8080

spring:
    application:
        name: kafka-producer-app
    kafka:
        bootstrap-servers: 192.168.1.5:9092
        producer:
            bootstrap-servers: "192.168.1.5:9092"
            retries: 1
            batch-size: 16384
            buffer-memory: 33554432
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            acks: 1
